export {History} from "./History/History"
export {Home} from "./Home/Home"
export {LikedVideos} from "./LikedVideos/LikedVideos"
export {Playlist} from "./PlayList/Playlist"
export {WatchLater} from "./WatchLater/WatchLater"
export {VideoDetail} from "./VideoDetail/VideoDetail"